[package]
name = "smitters"
version = "0.1.0"
edition = "2021"

description = "Smith chart, Volpert–Smith chart, egui"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kurbo = "*"
egui = "*"
eframe = "*"
env_logger = "*"
itertools-num = "*"
